env:
  DOCKER_COMPOSE_VERSION: 1.13.0
language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- gradle clean dockerize
- cd integrationTest
- docker-compose up -d
- docker ps -a
- gradle -i -b ../build.gradle -Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca intTest
after_success:
- if [ "$(. ./can-deploy.sh)" = "DEPLOY" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push opencadc/cadc-target-resolver;
  fi
- if [ "$(. ./can-deploy.sh)" != "DEPLOY" ]; then
      echo "Not deploying.";
  fi
addons:
  hosts: proxy.cadc.dao.nrc.ca
notifications:
  slack:
    secure: FMzP6Yk5MNDz1dvR9YvAaQmdPM5ul7AEpzu8wpBrr2N2Qm6Yeok217WelMzRu4Zak7Pr65oCEMvpAE9TiWRNzuZvMsIB/h2TU+JlLtjAJx1hhX4ME5YaLgIOhaBNyNG64gTr9TTLYuTP0S/Zuy952hmL4hS1OBFSjU7E0xJH156NISb10tQfcoi/axWxSQSBfKnAiSt6KmNMbSwU+RTyRcq+665lIeW4Pj2QJaRDi7LcPUQZbV1iDKJ0mEjYxCS+Gvz+Su0jBHL+GTv1KvKh54I4cHTL1QpQADWkHcAFbPB+XX0jxid2GIJUtHj2j8bIRjAofILJDxh6tcuBARU0aCgRzHB5g3b4t4Y30bMZCkL6+eGg9uUNWGJUIno50AwsCoPLXFkEAdeGvxuVMXtCGylNDXf+KSeh7+1ZHzWEAqcOZYo6GEZbDceeRiM7DhflI7yX4lRHVI6SfaZ5cV1S6Q9iBS2yJbFdLLp63Y5NWtLTVS6FEZKt7qQZCNaM0mkljv7kpPiQZ6mqS+iqvdZBieFQ4C47goP/CrxXR5yYi1kNpg2AZAP08rhbFVAALC4GMAtyflwhuVhlCbaxS9uZOc9i8bHmnTr2NEIUHcUbezNhx/fDszv2BIrjh1hLMfnSfe+uf/5xmUsfPvHUL5IjGauPPJRGFMQGyjtl/6YsXg0=